[tool.poetry]
name = "ringapp"
version = "1.0.0"
description = "Website app for the Database of Ring Theory"
authors = ["rschwiebert <databaseofringtheory@gmail.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.10"
asgiref = "3.5.1"
boto3 = "1.24.0"
dj-database-url = "0.5.0"
Django = "3.2.24"
django-mathfilters = "0.4.0"
django-publications = "1.1.0"
django-ratelimit = "2.0.0"
django-recaptcha = "2.0.6"
django-registration-redux = "2.9"
gunicorn = "20.1.0"
model-mommy = "1.6.0"
mpmath = "1.3.0"
Pillow = "10.2.0"
pytz = "2021.3"
PyYAML = "6.0"
six = "1.11.0"
sqlparse = "0.4.4"
sympy = "1.12"
whitenoise = "5.0.1"
dart-data = {git = "https://github.com/rschwiebert/dart_data.git", rev = "49953d3885693dc6d8fdf8df0be561b0532d39bb"}
psycopg2 = "2.9.3"
django-heroku = "0.3.1"
requests = "2.31.0"
cryptography = "42.0.2"
wheel = "0.38.1"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
